Python 3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
========= RESTART: C:\Users\user\Documents\105023051\20170921\ch3.py =========
20170987
>>> math
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    math
NameError: name 'math' is not defined
>>>   m         vc
  
SyntaxError: unexpected indent
>>> 
>>> import math
>>> help(help)
Help on _Helper in module _sitebuiltins object:

class _Helper(builtins.object)
 |  Define the builtin 'help'.
 |  
 |  This is a wrapper around pydoc.help that provides a helpful message
 |  when 'help' is typed at the Python interactive prompt.
 |  
 |  Calling help() at the Python prompt starts an interactive help session.
 |  Calling help(thing) prints help for the python object 'thing'.
 |  
 |  Methods defined here:
 |  
 |  __call__(self, *args, **kwds)
 |      Call self as a function.
 |  
 |  __repr__(self)
 |      Return repr(self).
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)

>>> help(print)
Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.

>>> f f f f f f f f   f f f  f f f   f    '
SyntaxError: invalid syntax
>>> f==22
Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    f==22
NameError: name 'f' is not defined
>>> f=22
>>> g==f
Traceback (most recent call last):
  File "<pyshell#9>", line 1, in <module>
    g==f
NameError: name 'g' is not defined
>>> g=f
>>> g
22
>>> f=v
Traceback (most recent call last):
  File "<pyshell#12>", line 1, in <module>
    f=v
NameError: name 'v' is not defined
>>> f=4
>>> g
22
>>> g
22
>>> g
22
g
>>> 
>>> g
22
>>> g
22
g
>>> 
>>> g
22
>>> g**g
341427877364219557396646723584
>>> g
22
>>> 2**2
4
>>> 22**22
341427877364219557396646723584
>>> '
SyntaxError: EOL while scanning string literal
>>> 
>>> 


>>> 

>>> 

>>> 

>>> 

>>> 

>>> 


>>> 
>>> 

>>> 

>>> 

>>> 

>>> 

>>> 


>>> 
>>> 


>>> 

>>> 


>>> 
>>> 


>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 


>>> 
>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 


>>> 

>>> 

>>> 

>>> 

>>> help(for)
SyntaxError: invalid syntax
>>> fffffffffffffffffffffffffff
Traceback (most recent call last):
  File "<pyshell#89>", line 1, in <module>
    fffffffffffffffffffffffffff
NameError: name 'fffffffffffffffffffffffffff' is not defined
>>> 

>>> 

>>> 


>>> 
>>> 


>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 


>>> 
>>> 
>>> ffkjjokpoposeodskdpokposesefdllsed;ed;lsedlosedl;sedl;sedfl;sdefsedfsefdlo;sefd;sefd;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;sel;dolos;s;osefefsfdl;sefl;sdlsld;klxcxcm,v,m.vcbn,mzxck;lsdfoewrp[p[qrw247095223799933333333eueirk bfcvbcvxrueia;;ujmrwea'09[e3w][q2\23320943Q90543''IHOTRTIRRRRRRR
																								       
SyntaxError: invalid syntax
>>> RRRRRRRRRRRedddddwei0;pol\]-=0[p;';'']osferwe49oo0pppllllllllllllllllllllllllllllwfegtyseufgyolw';/ohfs9uyoihklwrefsd8uiyhefrefrefrefrefrefrefrefrefrefrefrefrefrefrefrefrefrefrefrskjd;f;;;'ff'sfsf''sf's'f'sd'f'sd'f'q'efr'we'f''ewsf's'e'e''d'''''sdd]]]]]]]]]]]]]]]]]]]]]]]]]''sfd'fds''f'ff''f'fsf'ee;efffefeeeeeeeeeeeeeeeeeeeee'efs'fse'fs'dfsefs]f']s]'f']s][d\f]sf]psjpbvxzerfr'wefposefpodf.l/.,mvxcn,mnm v m n m""fijoijfhrh89uifvhbgfdfgdjhjfhdjhdjhdfjfhddhjggggggggggggggggggggggg
SyntaxError: unexpected character after line continuation character
>>> dddddddddd
Traceback (most recent call last):
  File "<pyshell#106>", line 1, in <module>
    dddddddddd
NameError: name 'dddddddddd' is not defined
>>> ''d
SyntaxError: invalid syntax
>>> ddd
Traceback (most recent call last):
  File "<pyshell#108>", line 1, in <module>
    ddd
NameError: name 'ddd' is not defined
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> sin(2)
Traceback (most recent call last):
  File "<pyshell#146>", line 1, in <module>
    sin(2)
NameError: name 'sin' is not defined
>>> inport math
SyntaxError: invalid syntax
>>> SyntaxError: invalid syntaxSyntaxError: invalid syntaxinport math
SyntaxError: invalid syntax
>>> import math
>>> sin(0.2)
Traceback (most recent call last):
  File "<pyshell#150>", line 1, in <module>
    sin(0.2)
NameError: name 'sin' is not defined
>>> help(sin)
Traceback (most recent call last):
  File "<pyshell#151>", line 1, in <module>
    help(sin)
NameError: name 'sin' is not defined
>>> import math,sin
Traceback (most recent call last):
  File "<pyshell#152>", line 1, in <module>
    import math,sin
ModuleNotFoundError: No module named 'sin'
>>> help(import)
SyntaxError: invalid syntax
>>> import math.log
Traceback (most recent call last):
  File "<pyshell#154>", line 1, in <module>
    import math.log
ModuleNotFoundError: No module named 'math.log'; 'math' is not a package
>>> math
<module 'math' (built-in)>
>>> x=10*math.sin(0.2)
>>> x
1.9866933079506122
>>> man(math)
Traceback (most recent call last):
  File "<pyshell#158>", line 1, in <module>
    man(math)
NameError: name 'man' is not defined
>>> help(man)
Traceback (most recent call last):
  File "<pyshell#159>", line 1, in <module>
    help(man)
NameError: name 'man' is not defined
>>> math.aba(-5)
Traceback (most recent call last):
  File "<pyshell#160>", line 1, in <module>
    math.aba(-5)
AttributeError: module 'math' has no attribute 'aba'
>>> math.aba() < int x ; x=5;>
SyntaxError: invalid syntax
>>> def 87():
	
SyntaxError: invalid syntax
>>> def 87():										print("興國盜版中資")
SyntaxError: invalid syntax
>>> def 87():									    print("興國盜版中資")
SyntaxError: invalid syntax
>>> def g87():									    print("興國盜版中資")
SyntaxError: invalid syntax
>>> def g87():									    print("興國盜版中資")
g87
SyntaxError: invalid syntax
>>> class g87
SyntaxError: invalid syntax
>>> help(g87)
Traceback (most recent call last):
  File "<pyshell#169>", line 1, in <module>
    help(g87)
NameError: name 'g87' is not defined
>>> help(class)
SyntaxError: invalid syntax
>>> type(g87)
Traceback (most recent call last):
  File "<pyshell#171>", line 1, in <module>
    type(g87)
NameError: name 'g87' is not defined
>>> 
>>> 

>>> 

>>> 

>>> 


>>> 
>>> 


>>> 
>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> 

>>> g87()
Traceback (most recent call last):
  File "<pyshell#189>", line 1, in <module>
    g87()
NameError: name 'g87' is not defined
>>> def g87():
    print("gg")

			    
>>> g87()
gg
>>> def g87():
    print("狗")

         

>>> g87()
狗
>>> ccc
Traceback (most recent call last):
  File "<pyshell#199>", line 1, in <module>
    ccc
NameError: name 'ccc' is not defined
>>> ccc
Traceback (most recent call last):
  File "<pyshell#200>", line 1, in <module>
    ccc
NameError: name 'ccc' is not defined
>>> cxcxcxcxcxcxc
Traceback (most recent call last):
  File "<pyshell#201>", line 1, in <module>
    cxcxcxcxcxcxc
NameError: name 'cxcxcxcxcxcxc' is not defined
cx
>>> xxxxxxxxx
Traceback (most recent call last):
  File "<pyshell#202>", line 1, in <module>
    xxxxxxxxx
NameError: name 'xxxxxxxxx' is not defined
>>> g
22
>>> 
>>> 
>>> ggg
Traceback (most recent call last):
  File "<pyshell#206>", line 1, in <module>
    ggg
NameError: name 'ggg' is not defined
>>> yy
Traceback (most recent call last):
  File "<pyshell#207>", line 1, in <module>
    yy
NameError: name 'yy' is not defined
>>> def g88():
    g87
    print("54")

                
>>> g88()
54
>>> def g88():
    g87()
    print("54")

                          
>>> g88()
狗
54
>>> python dog
SyntaxError: invalid syntax
>>> python
Traceback (most recent call last):
  File "<pyshell#217>", line 1, in <module>
    python
NameError: name 'python' is not defined
>>> help(python)
Traceback (most recent call last):
  File "<pyshell#218>", line 1, in <module>
    help(python)
NameError: name 'python' is not defined
>>> vvvvwwwwwwwwwwwWWWWWWWWWWWWVVVVVVVVVVVVvvvvvvvvvvvvvvVWVWVVWVWVWVVvvvvvvvvvvvvvvvvvvwwwwwwwwwwwwwwwvvvvvvv
Traceback (most recent call last):
  File "<pyshell#219>", line 1, in <module>
    vvvvwwwwwwwwwwwWWWWWWWWWWWWVVVVVVVVVVVVvvvvvvvvvvvvvvVWVWVVWVWVWVVvvvvvvvvvvvvvvvvvvwwwwwwwwwwwwwwwvvvvvvv
NameError: name 'vvvvwwwwwwwwwwwWWWWWWWWWWWWVVVVVVVVVVVVvvvvvvvvvvvvvvVWVWVVWVWVWVVvvvvvvvvvvvvvvvvvvwwwwwwwwwwwwwwwvvvvvvv' is not defined
>>> vvvvvvvvvvvvvvvvvvv0000000vvvvvvvvvvvvvvvv0000000000vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv0000000vvvvvvvvvvvvvvvv0000000000vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv000OO00vvvvvvvvvvvvvvvv0005555500vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
Traceback (most recent call last):
  File "<pyshell#220>", line 1, in <module>
    vvvvvvvvvvvvvvvvvvv0000000vvvvvvvvvvvvvvvv0000000000vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv0000000vvvvvvvvvvvvvvvv0000000000vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv000OO00vvvvvvvvvvvvvvvv0005555500vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
NameError: name 'vvvvvvvvvvvvvvvvvvv0000000vvvvvvvvvvvvvvvv0000000000vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv0000000vvvvvvvvvvvvvvvv0000000000vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv000OO00vvvvvvvvvvvvvv' is not defined
>>> klklml;'l;m'l;m;svd'['svdk;
SyntaxError: invalid syntax
>>> ssk
Traceback (most recent call last):
  File "<pyshell#222>", line 1, in <module>
    ssk
NameError: name 'ssk' is not defined
p
>>> soofj;dof gwaegtw
SyntaxError: invalid syntax
>>> cccchaha
Traceback (most recent call last):
  File "<pyshell#224>", line 1, in <module>
    cccchaha
NameError: name 'cccchaha' is not defined
>>> fuck
Traceback (most recent call last):
  File "<pyshell#225>", line 1, in <module>
    fuck
NameError: name 'fuck' is not defined
>>> ddd
Traceback (most recent call last):
  File "<pyshell#226>", line 1, in <module>
    ddd
NameError: name 'ddd' is not defined
>>> fuckpython
Traceback (most recent call last):
  File "<pyshell#227>", line 1, in <module>
    fuckpython
NameError: name 'fuckpython' is not defined
>>> ikjvvvvv
Traceback (most recent call last):
  File "<pyshell#228>", line 1, in <module>
    ikjvvvvv
NameError: name 'ikjvvvvv' is not defined
v
>>> vvvv
Traceback (most recent call last):
  File "<pyshell#229>", line 1, in <module>
    vvvv
NameError: name 'vvvv' is not defined
>>> vvvv
Traceback (most recent call last):
  File "<pyshell#230>", line 1, in <module>
    vvvv
NameError: name 'vvvv' is not defined
>>> vvvv
Traceback (most recent call last):
  File "<pyshell#231>", line 1, in <module>
    vvvv
NameError: name 'vvvv' is not defined
v
>>> vvv
Traceback (most recent call last):
  File "<pyshell#232>", line 1, in <module>
    vvv
NameError: name 'vvv' is not defined
>>> fvfvfvfvfvfvffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
Traceback (most recent call last):
  File "<pyshell#233>", line 1, in <module>
    fvfvfvfvfvfvffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
NameError: name 'fvfvfvfvfvfvffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff' is not defined
>>> 
>>> 
>>> def g88()
SyntaxError: invalid syntax
>>> def g88():
    print(x)

          
>>> g88(5)
Traceback (most recent call last):
  File "<pyshell#240>", line 1, in <module>
    g88(5)
TypeError: g88() takes 0 positional arguments but 1 was given
>>> g88()
1.9866933079506122
>>> def g88(x):
    print(x)

    
>>> g88(g87)
<function g87 at 0x0000000002F0C620>
>>> g88(5)
5
>>> kklklkkkkj
Traceback (most recent call last):
  File "<pyshell#246>", line 1, in <module>
    kklklkkkkj
NameError: name 'kklklkkkkj' is not defined
>>> g88(幹)
Traceback (most recent call last):
  File "<pyshell#247>", line 1, in <module>
    g88(幹)
NameError: name '幹' is not defined

>>> g88("幹")
幹

>>> 

>>> dg87
Traceback (most recent call last):
  File "<pyshell#250>", line 1, in <module>
    dg87
NameError: name 'dg87' is not defined
\
>>> def g87(a):
    x=aa
    return x

>>> g88(g87(5))
Traceback (most recent call last):
  File "<pyshell#255>", line 1, in <module>
    g88(g87(5))
  File "<pyshell#254>", line 2, in g87
    x=aa
NameError: name 'aa' is not defined
>>> def g87(a):
    x=a
    return x

>>> g88(g87(a))
Traceback (most recent call last):
  File "<pyshell#258>", line 1, in <module>
    g88(g87(a))
NameError: name 'a' is not defined
>>> g88(g87(5))
5
>>> bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
Traceback (most recent call last):
  File "<pyshell#260>", line 1, in <module>
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
NameError: name 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb' is not defined
>>> b
Traceback (most recent call last):
  File "<pyshell#261>", line 1, in <module>
    b
NameError: name 'b' is not defined
>>> b
Traceback (most recent call last):
b  File "<pyshell#262>", line 1, in <module>
    b
NameError: name 'b' is not defined

>>> 
b
>>> 
b
>>> b
Traceback (most recent call last):
  File "<pyshell#265>", line 1, in <module>
    b
NameError: name 'b' is not defined
b
>>> b
Traceback (most recent call last):
  File "<pyshell#266>", line 1, in <module>
    b
NameError: name 'b' is not defined
b
>>> b
Traceback (most recent call last):
  File "<pyshell#267>", line 1, in <module>
    b
NameError: name 'b' is not defined
>>> 
b
>>> 
b
>>> 
b
>>> 
>>>  bfg
 
SyntaxError: unexpected indent
>>> 
>>> f
4
>>> 
b
>>> 
>>> 
>>> 
>>> 
>>> g
22
b
g
>>> 
>>> 
>>> f
4
g
>>> 
>>> g
22
f
>>> 
>>> 
>>> 
>>> 
>>> fgbgffggbgfbgf
Traceback (most recent call last):
  File "<pyshell#290>", line 1, in <module>
    fgbgffggbgfbgf
NameError: name 'fgbgffggbgfbgf' is not defined
b
>>> 
>>> gf
Traceback (most recent call last):
  File "<pyshell#292>", line 1, in <module>
    gf
NameError: name 'gf' is not defined
>>> b
>>> gf
Traceback (most recent call last):
  File "<pyshell#294>", line 1, in <module>
    gf
NameError: name 'gf' is not defined
b
>>> fg
Traceback (most recent call last):
  File "<pyshell#295>", line 1, in <module>
    fg
NameError: name 'fg' is not defined
bfg
>>> 
>>> b
Traceback (most recent call last):
  File "<pyshell#297>", line 1, in <module>
    b
NameError: name 'b' is not defined
fg
>>> gfed
Traceback (most recent call last):
  File "<pyshell#298>", line 1, in <module>
    gfed
NameError: name 'gfed' is not defined
>>> fgerg
Traceback (most recent call last):
  File "<pyshell#299>", line 1, in <module>
    fgerg
NameError: name 'fgerg' is not defined
>>> er
Traceback (most recent call last):
  File "<pyshell#300>", line 1, in <module>
    er
NameError: name 'er' is not defined
h
>>> 
>>> g
22
f
>>> s
Traceback (most recent call last):
  File "<pyshell#303>", line 1, in <module>
    s
NameError: name 's' is not defined
d
>>> 
fr
>>> df
Traceback (most recent call last):
  File "<pyshell#305>", line 1, in <module>
    df
NameError: name 'df' is not defined
>>> fd
Traceback (most recent call last):
  File "<pyshell#306>", line 1, in <module>
    fd
NameError: name 'fd' is not defined
df
>>> fdfd
Traceback (most recent call last):
  File "<pyshell#307>", line 1, in <module>
    fdfd
NameError: name 'fdfd' is not defined
>>> f*f
16
>>> f*g
88
>>> dddddddddddddddddddd
Traceback (most recent call last):
  File "<pyshell#310>", line 1, in <module>
    dddddddddddddddddddd
NameError: name 'dddddddddddddddddddd' is not defined
>>> ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
Traceback (most recent call last):
  File "<pyshell#311>", line 1, in <module>
    ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
NameError: name 'ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd' is not defined
>>> gggggggggggggggggg
Traceback (most recent call last):
  File "<pyshell#312>", line 1, in <module>
    gggggggggggggggggg
NameError: name 'gggggggggggggggggg' is not defined
>>> bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
Traceback (most recent call last):
  File "<pyshell#313>", line 1, in <module>
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
NameError: name 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb' is not defined
>>> private
Traceback (most recent call last):
  File "<pyshell#314>", line 1, in <module>
    private
NameError: name 'private' is not defined
>>> def private ff5();
SyntaxError: invalid syntax
>>> def private ff5():
	
SyntaxError: invalid syntax
>>> def private ff5():                                      			    x=5
SyntaxError: invalid syntax
>>> 
>>> gamma
Traceback (most recent call last):
  File "<pyshell#319>", line 1, in <module>
    gamma
NameError: name 'gamma' is not defined
>>> ddddededededfffervffrfvvvfffffffffgggggggggggrrrrrrrrrreeeeeeeeeeeeeeeeeeeeedfgggggggggggggggggghbcvbdfgweertrtwhdjnfgndc bFVETRY6RUTKHNGVMVBCNVBCDFHW3E423425345RETY658 789;8PO;L,.,M/;L"
SyntaxError: invalid syntax
>>> P-[]P[
	
SyntaxError: invalid syntax
>>> L;'L;KKKKKKKKKKKKKKKK;L'L'L'L'L'L'L'L'''999999'8'''''''''''K;';;LLIKIL9/'IKOYFFYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYFFFFFFFFFFFFFFFFFFFFFFFFFF
SyntaxError: invalid syntax
>>> NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
Traceback (most recent call last):
  File "<pyshell#323>", line 1, in <module>
    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NameError: name 'NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN' is not defined
>>> return f
SyntaxError: 'return' outside function
>>> help(return)
SyntaxError: invalid syntax
>>> 
>>> len(22)
Traceback (most recent call last):
  File "<pyshell#327>", line 1, in <module>
    len(22)
TypeError: object of type 'int' has no len()
>>> help(len)
Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.

>>> len(22./)
SyntaxError: invalid syntax
>>> len('好')
1

>>> 

>>> def c7(x):									    print('                                           '+x)

>>> c7(5)
Traceback (most recent call last):
  File "<pyshell#334>", line 1, in <module>
    c7(5)
  File "<pyshell#333>", line 1, in c7
    def c7(x):									    print('                                           '+x)
TypeError: must be str, not int
>>> c7("g")
                                           g
>>> def c7(x):									    a=len(x)
    print((70-a)*" "+x)
    
SyntaxError: unexpected indent
>>> def c7(x):									    a=len(x)
    print((70-a)*" "+x)
    
SyntaxError: unexpected indent
>>> 
>>> def c7(x):									    a=len(x)
    print((70-a)*" "+x)
    
SyntaxError: unexpected indent
>>> def c7(x):
    a=len(x)
    print((70-a)*" "+x)

    
>>> c7("肥豬")
                                                                    肥豬
>>> c7("fjsdijfo")
                                                              fjsdijfo
>>> def do2(d,f):
    d()
    d()
    f()
    f()

    
>>> def p2(x):
    print(x)
    print(x)

    
>>> do2(p2(ss),p2(ss))
Traceback (most recent call last):
  File "<pyshell#355>", line 1, in <module>
    do2(p2(ss),p2(ss))
NameError: name 'ss' is not defined
>>> do2(p2('ss'),p2('ss'))
ss
ss
ss
ss
Traceback (most recent call last):
  File "<pyshell#356>", line 1, in <module>
    do2(p2('ss'),p2('ss'))
  File "<pyshell#350>", line 2, in do2
    d()
TypeError: 'NoneType' object is not callable
>>> do2(p2('ss'),p2('ss'))
ss
ss
ss
ss
Traceback (most recent call last):
  File "<pyshell#357>", line 1, in <module>
    do2(p2('ss'),p2('ss'))
  File "<pyshell#350>", line 2, in do2
    d()
TypeError: 'NoneType' object is not callable
>>> def do4(f,x):
    f(x)
    f(x)

    
>>> do4(do2(),p2('math.sin(0.5)'))
Traceback (most recent call last):
  File "<pyshell#365>", line 1, in <module>
    do4(do2(),p2('math.sin(0.5)'))
TypeError: do2() missing 2 required positional arguments: 'd' and 'f'
>>> def do2(f,x):
    f(x)
    f(x)

    
>>> do4(do2(),p2('math.sin(0.5)'))
Traceback (most recent call last):
  File "<pyshell#370>", line 1, in <module>
    do4(do2(),p2('math.sin(0.5)'))
TypeError: do2() missing 2 required positional arguments: 'f' and 'x'
>>> do4(do2('uijuj'),p2())
Traceback (most recent call last):
  File "<pyshell#371>", line 1, in <module>
    do4(do2('uijuj'),p2())
TypeError: do2() missing 1 required positional argument: 'x'
>>> do4(do2(,'uijuj'),p2())
SyntaxError: invalid syntax
>>> do4(do2(p2("ff"),"ff"),p2("ff"))
ff
ff
Traceback (most recent call last):
  File "<pyshell#373>", line 1, in <module>
    do4(do2(p2("ff"),"ff"),p2("ff"))
  File "<pyshell#369>", line 2, in do2
    f(x)
TypeError: 'NoneType' object is not callable
>>> p2('g')
g
g
>>> do2(p2(),'f')
Traceback (most recent call last):
  File "<pyshell#375>", line 1, in <module>
    do2(p2(),'f')
TypeError: p2() missing 1 required positional argument: 'x'
>>> do2(p2('4'),'f')
4
4
Traceback (most recent call last):
  File "<pyshell#376>", line 1, in <module>
    do2(p2('4'),'f')
  File "<pyshell#369>", line 2, in do2
    f(x)
TypeError: 'NoneType' object is not callable
>>> def do2(f,x):
    f(x)
    f(x)

    
>>> do2(p2('4'),'f')
4
4
Traceback (most recent call last):
  File "<pyshell#381>", line 1, in <module>
    do2(p2('4'),'f')
  File "<pyshell#380>", line 2, in do2
    f(x)
TypeError: 'NoneType' object is not callable
>>> def p2():
    print()
    print()

    
>>> do2(p2(),'f')


Traceback (most recent call last):
  File "<pyshell#386>", line 1, in <module>
    do2(p2(),'f')
  File "<pyshell#380>", line 2, in do2
    f(x)
TypeError: 'NoneType' object is not callable
>>> def do2(f,x):
    f()
    f()
    return x

>>> def do4(f,x):
    f()
    f()
    f()
    f()
    return x

>>> def do2(f,x):
    f(x)
    f(x)

    
>>> def do4(f,x):
    do2(f,x)
    do2(f,x)

    
>>> do4(p2("g"),"g")
Traceback (most recent call last):
  File "<pyshell#407>", line 1, in <module>
    do4(p2("g"),"g")
TypeError: p2() takes 0 positional arguments but 1 was given
>>> do4(p2(),"g")


Traceback (most recent call last):
  File "<pyshell#408>", line 1, in <module>
    do4(p2(),"g")
  File "<pyshell#406>", line 2, in do4
    do2(f,x)
  File "<pyshell#403>", line 2, in do2
    f(x)
TypeError: 'NoneType' object is not callable
>>> 
>>> do4(p2,"g")
Traceback (most recent call last):
  File "<pyshell#410>", line 1, in <module>
    do4(p2,"g")
  File "<pyshell#406>", line 2, in do4
    do2(f,x)
  File "<pyshell#403>", line 2, in do2
    f(x)
TypeError: p2() takes 0 positional arguments but 1 was given
>>> p2("g")
Traceback (most recent call last):
  File "<pyshell#411>", line 1, in <module>
    p2("g")
TypeError: p2() takes 0 positional arguments but 1 was given
>>> def p2(x)
SyntaxError: invalid syntax
>>> def p2(x):
    print(x)
    print(x)

    
>>> do4(p2,"g")
g
g
g
g
g
g
g
g
>>> 
def do_twice(func, arg):
    """Runs a function twice.

    func: function object
    arg: argument passed to the function
    """
    func(arg)
    func(arg)


def print_twice(arg):
    """Prints the argument twice.

    arg: anything printable
    """
    print(arg)
    print(arg)


def do_four(func, arg):
    """Runs a function four times.

    func: function object
    arg: argument passed to the function
    """
    do_twice(func, arg)
    do_twice(func, arg)


do_twice(print_twice, 'spam')
print('')

do_four(print_twice, 'spam')
SyntaxError: invalid syntax
>>> def a+-():
	
SyntaxError: invalid syntax
>>> def a+-():
	
SyntaxError: invalid syntax
>>> def a1():
    print('+'+en" ")
    
SyntaxError: invalid syntax
>>> 
>>> def a1():
    print('+'+end' ')
    
SyntaxError: invalid syntax
>>> def a1():
    print('+'+end'')
    
SyntaxError: invalid syntax
>>> def a1():
    print('+'+end='')
    
SyntaxError: keyword can't be an expression
>>> def a1():
    print('+',end='')

    
>>> 
>>> def a1():
    print('+',5*'-')

    
>>> a1()
+ -----
>>> a1() a1()
SyntaxError: invalid syntax
>>> def a1():
    print('+- - -+- - -+')

    
>>> def a2();
SyntaxError: invalid syntax
>>> def a2():
    print("/      /      /"  )

    
>>> a1()
+- - -+- - -+
>>> a2()
/      /      /
>>> def a2():
    print("/    /      /"  )

    
>>> def a3()
SyntaxError: invalid syntax
>>> def a3():
    a1()
    a2()

    
>>> a3()
+- - -+- - -+
/    /      /
>>> 	def a3():
    a1()
    a2()
    
SyntaxError: unexpected indent
>>> def a3():
    a1()
    a2()
    a2()
    a2()
    a1()

    
>>> a3()
+- - -+- - -+
/    /      /
/    /      /
/    /      /
+- - -+- - -+
>>> print('8',end=' ')
8 
>>> print('8',end='5')
85
>>> print('8 ',"6")
8  6
>>> print('8',"6")
8 6
>>> print('8',end=' ',"6")
SyntaxError: positional argument follows keyword argument
>>> print('8',end=' '+"6")
8 6
>>> def plus();
SyntaxError: invalid syntax
>>> def plus():
    print("+",end=" ")

    
>>> def minus():
    print("-",end=" ")

    
>>> def bar():
    print("/",end="  ')
	  
SyntaxError: EOL while scanning string literal
>>> 
>>> def bar():
    print("/",end=' ')

    
>>> def one():
    plus()
    minus()
    minus()
    minus()
    plus()
    minus()
    minus()
    minus()
    minus()
    plus()


              
>>> 
>>> one()
+ - - - + - - - - + 
>>> def bar():
    print("|         |         |")

    
>>> def ok():
    one()
    bar()
    one()
    bar()

    
>>> ok()
+ - - - + - - - - + |         |         |
+ - - - + - - - - + |         |         |
>>> def plus():
    print("+")

    
>>> def minus():
    print("-")

    
>>> ok()
+
-
-
-
+
-
-
-
-
+
|         |         |
+
-
-
-
+
-
-
-
-
+
|         |         |
>>> def one():
    print("+ - - - - + - - - - +",end=" ")

    
>>> def two():
    print("|         |         |",end=" ")

    
>>> def do3(x):
    x()
    x()
    x()

    
>>> def ok():
    one()
    do3(two)
    one()
    do3(two)

    
>>> ok()
+ - - - - + - - - - + |         |         | |         |         | |         |         | + - - - - + - - - - + |         |         | |         |         | |         |         | 
>>> def one():
    print("+ - - - - + - - - - +")
    def two():
        print("|         |         |")

        
>>> ok()
+ - - - - + - - - - +
|         |         | |         |         | |         |         | + - - - - + - - - - +
|         |         | |         |         | |         |         | 
>>> two()
|         |         | 
>>> two()+one()
|         |         | + - - - - + - - - - +
Traceback (most recent call last):
  File "<pyshell#527>", line 1, in <module>
    two()+one()
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
>>> ok()
+ - - - - + - - - - +
|         |         | |         |         | |         |         | + - - - - + - - - - +
|         |         | |         |         | |         |         | 
>>> def ok()
SyntaxError: invalid syntax
>>> def ok():
    one()
    two()
    two()
    one()

    
>>> ok()
+ - - - - + - - - - +
|         |         | |         |         | + - - - - + - - - - +
>>> def one():
    print("+ - - - - + - - - - +")
    def ok():
    one()
    
SyntaxError: expected an indented block
>>> def one():
    print("+ - - - - + - - - - +")

    
>>> def two()
SyntaxError: invalid syntax
>>> def two():
    print("|         |         |")

    
>>> def ok():
    one()
    do3(two)
    one()
    do3()
    one()

    
>>> ok()
+ - - - - + - - - - +
|         |         |
|         |         |
|         |         |
+ - - - - + - - - - +
Traceback (most recent call last):
  File "<pyshell#553>", line 1, in <module>
    ok()
  File "<pyshell#552>", line 5, in ok
    do3()
TypeError: do3() missing 1 required positional argument: 'x'
>>> def ok():
    one()
    do3(two)
    one()
    do3(two)
    one()

    
>>> ok()
+ - - - - + - - - - +
|         |         |
|         |         |
|         |         |
+ - - - - + - - - - +
|         |         |
|         |         |
|         |         |
+ - - - - + - - - - +
>>> 
